version: '3'

services:
  app:
    image: ppaquin/artifactsmmorust:latest
    environment:
      - API_URL_ARTIFACTSMMO=https://api.artifactsmmo.com
      - TOKEN_API_ARTIFACTSMMO=xxx
    networks:
      - artifactsmmorust-network
networks:
  artifactsmmorust-network:
#    driver: bridge